POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This is sent from a rest file.",
    "important": true
}

###
GET http://localhost:3001/api/notes/

###
DELETE http://localhost:3001/api/notes/681ae12c8a8513a98f1b3ef1

###
PUT http://localhost:3001/api/notes/68205ebd7775609f4c0afe80
Content-Type: application/json

{
    "content": "This is a modified note",
    "important": true
}

